spring.application.name=geeksclub-api
spring.docker.compose.lifecycle-management=start_only

######## App Configuration  #########
app.support-email=support@sivalabs.dev
app.application-url=http://localhost:4200
app.cors.path-pattern=/api/**
app.cors.allowed-origins=*
app.cors.allowed-methods=*
app.cors.allowed-headers=*

app.openapi.title=GeeksClub API
app.openapi.description=GeeksClub API Swagger Documentation
app.openapi.version=v1.0.0
app.openapi.contact.name=SivaLabs
app.openapi.contact.email=support@sivalabs.in

app.jwt.issuer=GeeksClub
app.jwt.expires-in-seconds=604800
app.jwt.private-key=${JWT_PRIVATE_KEY:classpath:certs/private.pem}
app.jwt.public-key=${JWT_PUBLIC_KEY:classpath:certs/public.pem}

springdoc.paths-to-match=/api/**
################### Security Configuration ##########################

################ Actuator #####################
management.endpoints.web.exposure.include=configprops,env,health,info,logfile,loggers
management.endpoint.health.access=unrestricted

################ Database #####################
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

######## Kafka Configuration  #########
# add host mapping 'broker' to 127.0.0.1 in /etc/hosts file
KAFKA_BROKER=broker:9092
spring.kafka.bootstrap-servers=${KAFKA_BROKER}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=${spring.application.name}
spring.kafka.consumer.auto-offset-reset=latest
#spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.kafka.consumer.properties.spring.json.trusted.packages=*

######## AI Configuration #########
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3

