spring.application.name=geeksclub-api
spring.docker.compose.lifecycle-management=start_only

######## App Configuration  #########
app.support-email=support@sivalabs.dev
app.application-url=http://localhost:4200
app.cors.path-pattern=/api/**
app.cors.allowed-origins=*
app.cors.allowed-methods=*
app.cors.allowed-headers=*

app.openapi.title=GeeksClub API
app.openapi.description=GeeksClub API Swagger Documentation
app.openapi.version=v1.0.0
app.openapi.contact.name=SivaLabs
app.openapi.contact.email=support@sivalabs.in

app.jwt.issuer=GeeksClub
app.jwt.expires-in-seconds=604800
app.jwt.private-key=classpath:certs/private.pem
app.jwt.public-key=classpath:certs/public.pem

springdoc.paths-to-match=/api/**
################### Security Configuration ##########################

################ Actuator #####################
management.endpoints.web.exposure.include=configprops,env,health,info,logfile,loggers
management.endpoint.health.access=unrestricted

################ Database #####################
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
